dict={101:'python',201:'java',301:'c',401:'c++'}
print(dict)
print(type(dict))
print("--------------------------------------")
print(dict[101])
print(dict[201])
print(dict[301])
print(dict[401])
dict[501]='SQL'
print("----------------------------------")
print(dict)
dict[101]='flutter'
print("-----------------------------------------")
print(dict)
print("--------------------------------")
del dict[301]
print(dict)
print("---------------------------------")
del(dict)
print(dict)