ple=('python','c','c++','java','dart','flutter','go-lang','react js','angular')
print("the positive index of tuple is:")
print(ple[0])
print(ple[1])
print(ple[2])
print(ple[3])
print(ple[4])
print(ple[5])
print(ple[6])
print(ple[7])
print(ple[8])
print("the negative index of tuple is:")
print(ple[-1])
print(ple[-2])
print(ple[-3])
print(ple[-4])
print(ple[-5])
print(ple[-6])
print(ple[-7])
print(ple[-8])
print(ple[-9])